### ISSUE TITLE
Formatter inserts incorrect `}`

### ISSUE THREAD

**Issue by krns** [100phlecs/tailwind_formatter#16]
The first time I tried the formatter in one of our projects it worked. The second time I got an FunctionClauseError `no function clause matching in Phoenix.LiveView.HTMLFormatter.to_tree/4`.

It turns out that the first run of the tailwind formatter formats the following

```elixir
    <div class={"h-6 " <> if @active, do: "bg-white", else: "bg-red"}></div>
```

to

```elixir
    <div class={"h-6"} <> if @active, do: "bg-white", else: "bg-red"}></div>
```

And this is invalid code because of the inserted `}` :-)

**Comment by krns** [comment]
I tried to tell the formatter to not format this code with `phx-no-format`.  Seems like the tailwind formatter isn't respecting the `phx-no-format` attribute.

**Comment by 100phlecs** [comment]
Thanks for the report!
I've not come across that style for class interpolation before. 
It's an interesting case, would need to rethink the regex strategy to predominantly target `{` & `}` as terminators instead of `{"` & `"}` or just plain quotes (as I've been expecting only a string as the inner block)

I do like the idea of supporting the `phx-no-format` attribute. The reason that works seamlessly for the `Liveview.HTMLFormatter` is because they're making an AST of all the HTML code & attributes, so they can then query if that attribute exists on the node before formatting.

In this solution, we're using regex, so I can't think of an immediately obvious way to correlate the primary regex (basically searching for `class={"*"}` right now) and associating it with the HTML node it's in.

A couple of options:
1. A quick compromise would be to have some sort of `tw-no-format` as a class name, which would be easy to check because it's within the class block.
2. Support the `phx-no-format` as well, but needs some way to associate the class block with the html block it is in. Maybe make an AST as well? Something to think about.

In either case, thanks for the test case. I'll check for `<>` as another "elixir function" to extract. 
Let me know if you run into any other sorting issues :^)

**Comment by 100phlecs** [comment]
I've set up some extremely naive support for string concatenation in #17 

Todo:

- [ ] Allow multiple concatenations (need a better split strategy)
- [ ] Make concatenation order agnostic (currently formatter depends on concatenated function being defined after the main string block)
- [ ] Support multiple strings(?)

I'm curious what other type of elixir blocks that aren't accounted for, beyond this concatenation.

**Comment by krns** [comment]
Thank you very much for your thoughts. Just tested your solution successfully.

This kind of conditional class construction is a legacy from some of our older projects, before LiveView features like `assign_new` and declarative assignments were available.

**Comment by 100phlecs** [comment]
Fixed with #30

**Comment by krns** [comment]
Hi @100phlecs, since version 0.4.0 `Phoenix.LiveView.Tokenizer` has been used to capture class attributes. Have these changes made it easier to support `phx-no-format`, since regex is no longer used?


We tried to use `phx-no-format` as a workaround of #72 (cc @flo0807).

**Comment by Flo0807** [comment]
> We tried to use phx-no-format as a workaround of https://github.com/100phlecs/tailwind_formatter/issues/72 (cc @Flo0807).

I've added support for `phx-no-format` in #73
